# Gray-Scott weak scaling with a single-GPU CUDA.jl baseline.
[Global]
models = ["cunumeric", "cupynumeric", "cudajl", "jacc", "dagger"]
n_warmup = 2
n_iter = 50
n_trial = 5
check_correctness = true
n_correctness_iter = 5
auto_size = false

[[grayscott]]
T = "Float32"
gpus = [1, 2, 4, 8]
cpus = 8
N = [28000, 39600, 56000, 79200]
M = [28000, 39600, 56000, 79200]
fusion = true
